window.CSM = {
 csrf: '',
 _tabId: '',
 _browserId: '',
 _authChannel: null,
 tabId(){if(this._tabId)return this._tabId;try{const saved=sessionStorage.getItem('csm-tab-id');if(saved&&/^[a-f0-9]{32}$/.test(saved))return this._tabId=saved;}catch(_){}const bytes=new Uint8Array(16);if(!window.crypto?.getRandomValues)throw new Error('This browser cannot securely identify this tab. Please update your browser.');window.crypto.getRandomValues(bytes);const id=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');this._tabId=id;try{sessionStorage.setItem('csm-tab-id',id);}catch(_){}return id;},
 browserId(){if(this._browserId)return this._browserId;try{const saved=localStorage.getItem('csm-browser-id');if(saved&&/^[a-f0-9]{32}$/.test(saved))return this._browserId=saved;}catch(_){}try{const match=document.cookie.match(/(?:^|;\s*)csm_browser_id=([a-f0-9]{32})(?:;|$)/);if(match)return this._browserId=match[1];}catch(_){}const bytes=new Uint8Array(16);if(!window.crypto?.getRandomValues)throw new Error('This browser cannot securely identify this browser session. Please update your browser.');window.crypto.getRandomValues(bytes);const id=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');this._browserId=id;try{localStorage.setItem('csm-browser-id',id);}catch(_){try{document.cookie='csm_browser_id='+id+'; Path=/; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'');}catch(_){}}return id;},
 notifyLogin(){const event={type:'login',tabId:this.tabId(),browserId:this.browserId(),nonce:Date.now()+':'+Math.random()};try{if(this._authChannel)this._authChannel.postMessage(event);}catch(_){}try{localStorage.setItem('csm-auth-tab-event',JSON.stringify(event));}catch(_){}},
 handleOtherTabLogin(tabId,browserId){if(!tabId||tabId===this.tabId()||browserId!==this.browserId())return;this.csrf='';if(location.pathname.toLowerCase().endsWith('/login.html')){this.api('auth/session').catch(()=>{});return;}location.replace('login.html?mode=signin&reason=another-tab');},
 async api(route,method='GET',data){const headers={Accept:'application/json','X-CSM-Tab-Id':this.tabId(),'X-CSM-Browser-Id':this.browserId()};if(method!=='GET')headers['X-CSRF-Token']=this.csrf;const form=data instanceof FormData;if(data&&!form)headers['Content-Type']='application/json';const response=await fetch('api/index.php?r='+route,{method,credentials:'same-origin',headers,body:data?(form?data:JSON.stringify(data)):undefined,cache:'no-store'});const body=await response.text();let result;try{result=body?JSON.parse(body):{};}catch(_){const suffix=response.status?` (HTTP ${response.status})`:'';throw new Error(`The PHP endpoint returned a non-JSON response${suffix}. Make sure this site is being served by PHP, then check the PHP error log if the problem continues.`);}if(!response.ok){if(response.status===401&&!['auth/session','auth/login','auth/register','auth/password/request','auth/password/reset'].includes(route))location.replace('login.html?mode=signin&reason=another-tab');throw new Error(result.error||'Request failed ('+response.status+').');}if(result?.csrf)this.csrf=result.csrf;if(route==='auth/login')this.notifyLogin();return result;},
 async upload(deckId,file){const body=new FormData();body.append('deckId',deckId);body.append('file',file);return this.api('documents','POST',body);},
 download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},
 cleanLegacyAuth(){try{const keys=['csm-account','csm-auth-session','csm-remembered-session'];if(keys.some(k=>localStorage.getItem(k)))localStorage.setItem('csm-legacy-notice','true');keys.forEach(k=>localStorage.removeItem(k));}catch(_){}},
 exportLegacy(){const data={note:'Unverified browser data. Not automatically assigned to an account.'};for(const key of ['csm-profile','csm-recent-activities'])try{data[key]=JSON.parse(localStorage.getItem(key)||'null');}catch(_){}this.download(data,'co-studymaxx-old-browser-data.json');}
};
try{if('BroadcastChannel' in window){window.CSM._authChannel=new BroadcastChannel('csm-auth-tabs');window.CSM._authChannel.addEventListener('message',event=>{if(event.data?.type==='login')window.CSM.handleOtherTabLogin(event.data.tabId,event.data.browserId);});}window.addEventListener('storage',event=>{if(event.key==='csm-auth-tab-event'&&event.newValue){try{const message=JSON.parse(event.newValue);if(message?.type==='login')window.CSM.handleOtherTabLogin(message.tabId,message.browserId);}catch(_){}}});}catch(_){}
CSM.cleanLegacyAuth();
