<?php
require dirname(__DIR__).'/server/bootstrap.php';require dirname(__DIR__).'/server/arena.php';
$route=$_GET['r']??'';$method=$_SERVER['REQUEST_METHOD'];header('Referrer-Policy: same-origin');header('X-Frame-Options: SAMEORIGIN');
if(!is_string($route))fail(400,'Invalid endpoint.');if(!in_array($method,['GET','POST','PATCH','DELETE'],true))fail(405,'Method not allowed.');if($method!=='GET')csrf();
if($route==='auth/session'&&$method==='GET'){$ok=false;if(isset($_SESSION['user_id'])){$u=query('SELECT auth_version FROM users WHERE id=?',[$_SESSION['user_id']])->fetch();$ok=$u&&(int)$u['auth_version']==($_SESSION['auth_version']??0);}respond(['authenticated'=>(bool)$ok,'csrf'=>$_SESSION['csrf'],'profile'=>$ok?profile($_SESSION['user_id']):null]);}
if(in_array($route,['auth/register','auth/login'],true)&&$method==='POST'){
 global $users;$data=input();$login=field($data,'username',254);$pass=password_value($data,'password');$bucket=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').':'.$route);$now=time();
 query('INSERT INTO auth_attempts (bucket,attempts,window_start) VALUES (?,1,?) ON DUPLICATE KEY UPDATE attempts=IF(window_start<?,1,attempts+1),window_start=IF(window_start<?,VALUES(window_start),window_start)',[$bucket,$now,$now-900,$now-900]);if((int)query('SELECT attempts FROM auth_attempts WHERE bucket=?',[$bucket])->fetchColumn()>30)fail(429,'Too many attempts. Try again in 15 minutes.');
 if($route==='auth/register'){$username=$login;if(!preg_match('/^[A-Za-z0-9_]{3,24}$/D',$username))fail(422,'Username must contain 3–24 letters, numbers, or underscores.');$email=field($data,'email',254);if(!filter_var($email,FILTER_VALIDATE_EMAIL))fail(422,'Enter a valid email address.');$normalizedEmail=function_exists('mb_strtolower')?mb_strtolower($email,'UTF-8'):strtolower($email);try{$users->register(uid(),$username,$normalizedEmail,password_hash($pass,PASSWORD_DEFAULT));}catch(PDOException $e){if($e->getCode()==='23000')fail(409,'That username or email is already registered.');throw $e;}respond(['message'=>'Account created. Please sign in.'],201);}
 $row=$users->byLogin($login);$hash=$row['password_hash']??'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.';if(!$row||!password_verify($pass,$hash))fail(401,'Incorrect username/email or password.');if(password_needs_rehash($hash,PASSWORD_DEFAULT))query('UPDATE users SET password_hash=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$row['id']]);
 $_SESSION=[];session_regenerate_id(true);$remember=($data['remember']??false)===true;$until=time()+($remember?2592000:43200);$_SESSION=['user_id'=>$row['id'],'auth_version'=>(int)$row['auth_version'],'expires_at'=>$until,'csrf'=>bin2hex(random_bytes(32))];setcookie(session_name(),session_id(),['expires'=>$remember?$until:0,'path'=>'/','secure'=>(bool)$config['secure_cookie'],'httponly'=>true,'samesite'=>'Lax']);query('DELETE FROM auth_attempts WHERE bucket=?',[$bucket]);respond(['profile'=>profile($row['id']),'csrf'=>$_SESSION['csrf']]);
}
$user=user_id();global $users,$decksService,$bombcardsService,$materialsService,$progressService,$bombstyleService;
if($route==='auth/logout'&&$method==='POST'){$_SESSION=[];session_destroy();setcookie(session_name(),'', ['expires'=>time()-3600,'path'=>'/','secure'=>(bool)$config['secure_cookie'],'httponly'=>true,'samesite'=>'Lax']);respond(['ok'=>true]);}
if($route==='workspace'&&$method==='GET')respond(workspace($user));
if($route==='profile'&&$method==='PATCH'){$data=input();$p=query('SELECT * FROM profiles WHERE user_id=? FOR UPDATE',[$user])->fetch();if(isset($data['displayName'])){$name=field($data,'displayName',40);if($name!==$p['display_name']){if($p['name_changed_at']&&strtotime($p['name_changed_at'])>time()-604800)fail(409,'Display names can only change once every 7 days.');query('UPDATE profiles SET display_name=?,name_changed_at=CURRENT_TIMESTAMP(3) WHERE user_id=?',[$name,$user]);}}if(isset($data['avatar'])){$avatar=field($data,'avatar',16);if(!in_array($avatar,['ember','ocean','mint','violet','sunset','slate'],true))fail(422,'Invalid avatar.');query('UPDATE profiles SET avatar=? WHERE user_id=?',[$avatar,$user]);}respond(profile($user));}
if($route==='auth/password'&&$method==='POST'){$data=input();$old=password_value($data,'currentPassword');$next=password_value($data,'newPassword');$row=query('SELECT password_hash,auth_version FROM users WHERE id=? FOR UPDATE',[$user])->fetch();if(!password_verify($old,$row['password_hash']))fail(422,'Current password is incorrect.');$users->setPassword($user,password_hash($next,PASSWORD_DEFAULT));$_SESSION['auth_version']=(int)$row['auth_version']+1;session_regenerate_id(true);respond(['ok'=>true]);}
if($route==='decks'){
 if($method==='GET')respond(deck_data(owned_deck(id_field($_GET),$user)));
 if(in_array($method,['POST','PATCH'],true)){$data=input();$title=field($data,'title',160);$subject=field($data,'subject',160,false);$category=field($data,'category',80,false)?:'Recent';$id=$method==='PATCH'?id_field($data):uid();$db->beginTransaction();if($method==='PATCH'){$old=owned_deck($id,$user);$decksService->update($id,$title,$subject,$category);}else$decksService->create($id,$user,$title,$subject,$category);
  if(array_key_exists('cards',$data)){if(!is_array($data['cards'])||count($data['cards'])>1000)fail(422,'Invalid card list.');$keep=[];foreach($data['cards'] as $i=>$card){if(!is_array($card))fail(422,'Invalid Bombcard.');$cardId=isset($card['id'])&&preg_match('/^[a-f0-9]{32}$/D',(string)$card['id'])?$card['id']:null;$keep[]=save_card($card,$id,$cardId,$i);}foreach($bombcardsService->forDeck($id) as $card)if(!in_array($card['id'],$keep,true))$bombcardsService->delete($card['id'],$id);}
  activity($user,$id,$title,'Reviewer','library',$method==='POST'?'Created':'Edited');$db->commit();respond(deck_data(owned_deck($id,$user)),$method==='POST'?201:200);}
 if($method==='DELETE'){$id=id_field(input());owned_deck($id,$user);$names=query('SELECT stored_name FROM documents WHERE deck_id=? AND user_id=?',[$id,$user])->fetchAll(PDO::FETCH_COLUMN);$decksService->delete($id,$user);foreach($names as $name){$path=$config['upload_dir'].'/'.$name;if(is_file($path))unlink($path);}respond(['ok'=>true]);}
}
if($route==='cards'&&in_array($method,['POST','PATCH','DELETE'],true)){$data=input();$deck=owned_deck(id_field($data,'deckId'),$user);$db->beginTransaction();if($method==='DELETE'){$id=id_field($data);if(!$bombcardsService->delete($id,$deck['id']))fail(404,'Bombcard not found.');}else{$position=(int)query('SELECT COALESCE(MAX(position),-1)+1 FROM cards WHERE deck_id=?',[$deck['id']])->fetchColumn();$id=save_card($data,$deck['id'],$method==='PATCH'?id_field($data):null,$position);}activity($user,$deck['id'],$deck['title'],'Bombcards','library',$method==='DELETE'?'Removed':($method==='POST'?'Created':'Edited'));$db->commit();respond(['id'=>$id],$method==='POST'?201:200);}
if($route==='documents'&&$method==='POST'){
 $deck=owned_deck(id_field($_POST,'deckId'),$user);$file=$_FILES['file']??null;if(!$file||!is_array($file)||is_array($file['error']??null))fail(422,'Choose a PDF.');if($file['error']!==UPLOAD_ERR_OK)fail(413,'Upload failed; check the PDF size and PHP limits.');if($file['size']<5||$file['size']>$config['max_upload_bytes'])fail(413,'PDFs must be no larger than 10 MB.');$name=basename(str_replace('\\','/',$file['name']));if(strtolower(pathinfo($name,PATHINFO_EXTENSION))!=='pdf'||text_length($name)>255)fail(422,'Only PDF files are allowed.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$h=fopen($file['tmp_name'],'rb');$magic=fread($h,5);fclose($h);if($mime!=='application/pdf'||$magic!=='%PDF-')fail(422,'Invalid PDF content.');$dir=$config['upload_dir'];if(!is_dir($dir)&&!mkdir($dir,0700,true))fail(500,'Private file storage is unavailable.');$real=realpath($dir);$root=realpath(dirname(__DIR__));if(str_starts_with(strtolower(str_replace('\\','/',$real).'/'),strtolower(str_replace('\\','/',$root).'/')))fail(503,'PDF storage must be outside the public project directory.');$id=uid();$stored=uid().'.pdf';$path=$real.DIRECTORY_SEPARATOR.$stored;if(!move_uploaded_file($file['tmp_name'],$path))fail(500,'Could not store the PDF.');try{$db->beginTransaction();$materialsService->add($id,$deck['id'],$user,$name,$stored,$mime,(int)$file['size']);activity($user,$deck['id'],$name,'PDF','library','Uploaded');$db->commit();}catch(Throwable $e){if(is_file($path))unlink($path);throw $e;}respond(['id'=>$id,'title'=>$name,'size'=>(int)$file['size'],'url'=>'api/index.php?r=documents/file&id='.$id],201);
}
if($route==='documents'&&$method==='DELETE'){$doc=$materialsService->remove(id_field(input()),$user);if(!$doc)fail(404,'Material not found.');$path=$config['upload_dir'].'/'.$doc['stored_name'];if(is_file($path))unlink($path);respond(['ok'=>true]);}
if($route==='documents/file'&&$method==='GET'){$doc=owned_document(id_field($_GET),$user);$path=$config['upload_dir'].'/'.$doc['stored_name'];if(!is_file($path))fail(404,'PDF missing from file storage.');session_write_close();header('Content-Type: application/pdf');header('Content-Length: '.filesize($path));$disp=($_GET['download']??'')==='1'?'attachment':'inline';header("Content-Disposition: $disp; filename=\"document.pdf\"; filename*=UTF-8''".rawurlencode($doc['title']));header('Cache-Control: private, no-store');header('X-Content-Type-Options: nosniff');header("Content-Security-Policy: frame-ancestors 'self'; base-uri 'none'");readfile($path);exit;}
if($route==='highlights/card'&&$method==='POST'){
 $data=input();$doc=owned_document(id_field($data,'documentId'),$user);$text=field($data,'text',10000);$counterpart=field($data,'counterpart',10000);$page=$data['page']??1;$color=field($data,'color',7);$purpose=field($data,'purpose',16);$selection=selection_json($data);
 if(!$selection||!in_array($purpose,['question','answer'],true)||!is_int($page)||$page<1||$page>100000||!preg_match('/^#[0-9a-fA-F]{6}$/D',$color))fail(422,'Choose whether the excerpt is the question or answer.');
 $prompt=$purpose==='question'?$text:$counterpart;$answer=$purpose==='answer'?$text:$counterpart;$position=(int)query('SELECT COALESCE(MAX(position),-1)+1 FROM cards WHERE deck_id=?',[$doc['deck_id']])->fetchColumn();
 $db->beginTransaction();$cardId=save_card(['type'=>'IDENTIFICATION','prompt'=>$prompt,'correctAnswer'=>$answer],$doc['deck_id'],null,$position);$id=uid();query('INSERT INTO highlights(id,document_id,page_number,note_text,color,purpose,selection_json,card_id) VALUES(?,?,?,?,?,?,?,?)',[$id,$doc['id'],$page,$text,$color,$purpose,$selection,$cardId]);activity($user,$doc['deck_id'],$doc['title'],'PDF-to-Bombcard','highlighter','Created');$db->commit();
 respond(['cardId'=>$cardId,'highlight'=>['id'=>$id,'text'=>$text,'page'=>$page,'color'=>$color,'purpose'=>$purpose,'selection'=>json_decode($selection,true),'cardId'=>$cardId]],201);
}
if($route==='highlights'){$data=$method==='GET'?$_GET:input();$doc=owned_document(id_field($data,'documentId'),$user);if($method==='GET'){$rows=query('SELECT id,note_text text,page_number page,color,purpose,selection_json,card_id cardId FROM highlights WHERE document_id=? ORDER BY page_number,created_at',[$doc['id']])->fetchAll();foreach($rows as &$row){$row['selection']=$row['selection_json']?json_decode($row['selection_json'],true):[];unset($row['selection_json']);}respond($rows);}if($method==='DELETE'){if(isset($data['id']))query('DELETE FROM highlights WHERE id=? AND document_id=?',[id_field($data),$doc['id']]);else query('DELETE FROM highlights WHERE document_id=?',[$doc['id']]);respond(['ok'=>true]);}if(in_array($method,['POST','PATCH'],true)){$text=field($data,'text',10000);$page=$data['page']??1;$color=field($data,'color',7);$purpose=$data['purpose']??'note';$selection=selection_json($data);if(!is_int($page)||$page<1||$page>100000||!preg_match('/^#[0-9a-fA-F]{6}$/D',$color)||!is_string($purpose)||!in_array($purpose,['note','question','answer'],true))fail(422,'Invalid note page, role, or color.');$id=$method==='PATCH'?id_field($data):uid();if($method==='PATCH'){if(!query('SELECT id FROM highlights WHERE id=? AND document_id=?',[$id,$doc['id']])->fetch())fail(404,'Note not found.');query('UPDATE highlights SET note_text=?,page_number=?,color=?,purpose=?,selection_json=? WHERE id=?',[$text,$page,$color,$purpose,$selection,$id]);}else query('INSERT INTO highlights(id,document_id,page_number,note_text,color,purpose,selection_json) VALUES(?,?,?,?,?,?,?)',[$id,$doc['id'],$page,$text,$color,$purpose,$selection]);respond(['id'=>$id,'text'=>$text,'page'=>$page,'color'=>$color,'purpose'=>$purpose,'selection'=>$selection?json_decode($selection,true):[]],$method==='POST'?201:200);}}
if($route==='study/progress'&&$method==='GET')respond($progressService->forUser($user));
if($route==='study/progress'&&$method==='POST'){$data=input();$card=id_field($data,'bombcardId');if(!query('SELECT c.id FROM cards c JOIN decks d ON d.id=c.deck_id WHERE c.id=? AND d.user_id=?',[$card,$user])->fetch())fail(404,'Bombcard not found.');$result=field($data,'result',16);$progressService->record($user,$card,$result);respond(['ok'=>true],201);}
if($route==='activity'&&$method==='POST'){$data=input();$deck=isset($data['deckId'])?owned_deck(id_field($data,'deckId'),$user):null;$screen=field($data,'screen',32);if(!in_array($screen,['library','flashcards','highlighter','game','creator'],true))fail(422,'Invalid study screen.');activity($user,$deck['id']??null,field($data,'material',255),field($data,'mode',80),$screen,'Opened');respond(['ok'=>true],201);}
if($route==='account/export'&&$method==='GET'){$data=workspace($user);$data['exportedAt']=gmdate(DATE_ATOM);$data['highlights']=[];$data['arenaHistory']=[];$data['activities']=query('SELECT id,deck_id deckId,material,mode,screen,status,accuracy,created_at FROM study_activity WHERE user_id=? ORDER BY created_at DESC',[$user])->fetchAll();foreach($data['decks'] as $deck)foreach($deck['documents'] as $doc)$data['highlights'][$doc['id']]=query('SELECT id,page_number,note_text,color,purpose,selection_json,card_id cardId,created_at FROM highlights WHERE document_id=?',[$doc['id']])->fetchAll();foreach($bombstyleService->history($user,500) as $s)$data['arenaHistory'][]=arena_view($s);header('Content-Disposition: attachment; filename="co-studymaxx-export.json"');respond($data);}
arena_routes($route,$method,$user);fail(404,'Endpoint not found.');
